services:
  pgdb:
    image: postgres:17.5-alpine
    container_name: pgdb
    environment:
      POSTGRES_DB: xegality_db
      POSTGRES_USER: xegality
      POSTGRES_PASSWORD: xegality
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xegality -d xegality_db"]
      interval: 5s
      timeout: 10s
      retries: 5
